'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'fr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    'nav.merchantLogin': 'Merchant Login',
    'nav.getStarted': 'Get Started',
    'nav.home': 'Home',
    'nav.simulator': 'Try Demo',
    'hero.badge': 'The future of loyalty is here',
    'hero.title1': 'The digital loyalty card',
    'hero.title2': 'that just works.',
    'hero.subtitle': 'Replace paper stamp cards with a secure, instant digital experience. No app downloads, no mandatory accounts, zero friction.',
    'hero.cta1': 'Start for free',
    'hero.cta2': 'Try the demo',
    'how.title': 'Faster than paper.',
    'how.subtitle': 'A seamless experience for your customers.',
    'how.step1.title': '1. Scan',
    'how.step1.desc': 'Customer scans the dynamic QR code on your counter display. No app required.',
    'how.step2.title': '2. Earn',
    'how.step2.desc': 'A web page opens instantly. One tap to validate the purchase and earn a point.',
    'how.step3.title': '3. Secure',
    'how.step3.desc': 'QR codes change every 60 seconds and are cryptographically signed to prevent fraud.',
    'footer.rights': 'All rights reserved.',
    'login.title': 'Merchant Login',
    'login.subtitle': 'Sign in to manage your loyalty program',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.demoTitle': 'Demo account',
    'login.demoDesc': 'Try all features with the preconfigured demo account — no setup required.',
    'login.demoFill': 'Use demo credentials',
    'earn.invalidQr': 'Invalid QR code',
    'earn.failedValidate': 'Failed to validate QR code',
    'earn.pointAdded': 'Point Added!',
    'earn.pointEarned': 'You earned 1 loyalty point.',
    'earn.error': 'Error',
    'earn.failedAdd': 'Failed to add point',
    'earn.unexpected': 'An unexpected error occurred',
    'earn.magicSent': 'Magic Link Sent',
    'earn.magicDesc': 'Check your email to link your account and earn a bonus point!',
    'earn.failedMagic': 'Failed to send magic link',
    'earn.oops': 'Oops!',
    'earn.wrong': 'Something went wrong',
    'earn.digitalCard': 'Digital Loyalty Card',
    'earn.rewardUnlocked': '🎉 Reward Unlocked!',
    'earn.showScreen': 'Show this screen to the staff to redeem your reward.',
    'earn.redeem': 'Redeem Reward',
    'earn.validate': 'Validate my purchase',
    'earn.savePoints': 'Save my points (+1 bonus)',
    'earn.recent': 'Recent Activity',
    'earn.plusOne': '+1 Point',
    'earn.saveTitle': 'Save your points',
    'earn.saveDesc': 'Enter your email to save your progress. We\'ll send you a magic link to sign in. Earn a bonus point for linking!',
    'earn.email': 'Email address',
    'earn.sendMagic': 'Send Magic Link',
    'earn.waitingValidation': 'Waiting for validation',
    'earn.askMerchant': 'Please ask the merchant to approve your scan.',
    'earn.validationRejected': 'Validation rejected',
    'earn.merchantRejected': 'The merchant rejected your validation request.',
    'earn.closeTab': 'Close this tab',
    'earn.cooldown': 'Wait before scanning again',
    'earn.qrExpired': 'QR code expired',
    'earn.qrExpiredTitle': 'QR code expired',
    'earn.qrExpiredDesc': 'This QR code has expired. Ask the merchant to refresh it, then scan again.',
    'earn.close': 'Close',
    'earn.eduDesc': 'Your points are saved in this browser. Changing phones or clearing your browsing data could make you lose them.',
    'earn.eduCta': 'Link your account — it\'s free and takes 10 seconds.',
    'earn.protectTitle': 'Keep your points safe',
    'earn.protectDesc': 'Sign in to back up your points across all your devices.',
    'earn.saveWithGoogle': 'Continue with Google',
    'earn.saveWithFacebook': 'Continue with Facebook',
    'earn.or': 'or',
    'merchant.failedLoad': 'Failed to load dashboard',
    'merchant.configSaved': 'Configuration saved successfully',
    'merchant.failedConfig': 'Failed to save configuration',
    'merchant.copied': 'Copied to clipboard',
    'merchant.failedData': 'Failed to load merchant data.',
    'merchant.title': 'Trelio',
    'merchant.logout': 'Logout',
    'merchant.welcome': 'Welcome, ',
    'merchant.manage': 'Manage your loyalty program and track performance.',
    'merchant.overview': 'Overview',
    'merchant.settings': 'Settings',
    'merchant.integration': 'Integration',
    'merchant.totalScans': 'Total Scans',
    'merchant.uniqueUsers': 'Unique Customers',
    'merchant.rewardsRedeemed': 'Rewards Redeemed',
    'merchant.programConfig': 'Program Configuration',
    'merchant.storeName': 'Store Name',
    'merchant.rewardThreshold': 'Reward Threshold (Points needed)',
    'merchant.rewardDesc': 'Reward Description',
    'merchant.egCoffee': 'e.g., Free Coffee',
    'merchant.showQrCode': 'Show my QR code',
    'merchant.backToDashboard': 'Back to Dashboard',
    'merchant.failedLoadQr': 'Failed to load QR code',
    'merchant.scanQrDesc': 'Scan this QR code to earn loyalty points. It updates automatically every 60 seconds.',
    'merchant.validationRequests': 'Validation Requests',
    'merchant.waitingCustomers': 'Waiting for customers to scan...',
    'merchant.newRequest': 'New Request',
    'merchant.approve': 'Approve',
    'merchant.reject': 'Reject',
    'merchant.requestApproved': 'Request approved',
    'merchant.requestRejected': 'Request rejected',
    'merchant.failedProcessRequest': 'Failed to process request',
    'merchant.validationMode': 'Validation Mode',
    'merchant.validationModeDesc': 'Choose how customers earn points.',
    'merchant.modeAutomatic': 'Automatic',
    'merchant.modeAutomaticDesc': 'Points are added instantly when a customer scans and validates.',
    'merchant.modeManual': 'Manual',
    'merchant.modeManualDesc': 'You must approve each validation request in real-time.',
    'merchant.saveChanges': 'Save Changes',
    'merchant.apiCreds': 'API Credentials',
    'merchant.useCreds': 'Use these credentials to generate QR codes on your e-ink devices.',
    'merchant.merchantId': 'Merchant ID',
    'merchant.secretKey': 'Secret Key',
    'merchant.keepSecret': 'Keep this secret',
    'merchant.doNotShare': 'Do not share your secret key. It is used to sign QR codes and prevent fraud.',
    'merchant.recentScans': 'Recent Scans',
    'merchant.searchPlaceholder': 'Search email or device ID...',
    'merchant.filter': 'Filter',
    'merchant.dateAndTime': 'Date & Time',
    'merchant.customer': 'Customer',
    'merchant.type': 'Type',
    'merchant.device': 'Device',
    'merchant.anonymous': 'Anonymous',
    'merchant.registered': 'Registered',
    'merchant.noScans': 'No scans found matching your filters.',
    'merchant.showing': 'Showing',
    'merchant.to': 'to',
    'merchant.of': 'of',
    'merchant.results': 'results',
    'merchant.previous': 'Previous',
    'merchant.next': 'Next',
    'sim.failedLoad': 'Failed to load QR code',
    'sim.checkEnv': 'Failed to load QR code. Check environment variables.',
    'sim.scan': 'Scan to earn points!',
    'sim.coffee': '1 coffee = 1 point',
    'sim.action': 'Simulator Action',
    'sim.openView': 'Open customer view in new tab',
  },
  fr: {
    'nav.merchantLogin': 'Connexion Commerçant',
    'nav.getStarted': 'Commencer',
    'nav.home': 'Accueil',
    'nav.simulator': 'Essayer la démo',
    'hero.badge': 'L\'avenir de la fidélité est là',
    'hero.title1': 'La carte de fidélité numérique',
    'hero.title2': 'qui fonctionne, tout simplement.',
    'hero.subtitle': 'Remplacez les cartes à tampons par une expérience numérique instantanée et sécurisée. Pas de téléchargement, pas de compte obligatoire, zéro friction.',
    'hero.cta1': 'Commencer gratuitement',
    'hero.cta2': 'Essayer la démo',
    'how.title': 'Plus rapide que le papier.',
    'how.subtitle': 'Une expérience fluide pour vos clients.',
    'how.step1.title': '1. Scanner',
    'how.step1.desc': 'Le client scanne le QR code dynamique sur votre comptoir. Aucune application requise.',
    'how.step2.title': '2. Gagner',
    'how.step2.desc': 'Une page web s\'ouvre instantanément. Un clic pour valider l\'achat et gagner un point.',
    'how.step3.title': '3. Sécurisé',
    'how.step3.desc': 'Les QR codes changent toutes les 60 secondes et sont signés cryptographiquement pour éviter la fraude.',
    'footer.rights': 'Tous droits réservés.',
    'login.title': 'Connexion Commerçant',
    'login.subtitle': 'Connectez-vous pour gérer votre programme de fidélité',
    'login.email': 'Adresse e-mail',
    'login.password': 'Mot de passe',
    'login.submit': 'Se connecter',
    'login.demoTitle': 'Compte démo',
    'login.demoDesc': 'Explorez toutes les fonctionnalités avec le compte démo préconfiguré — sans configuration requise.',
    'login.demoFill': 'Utiliser les identifiants démo',
    'earn.invalidQr': 'QR code invalide',
    'earn.failedValidate': 'Échec de la validation du QR code',
    'earn.pointAdded': 'Point ajouté !',
    'earn.pointEarned': 'Vous avez gagné 1 point de fidélité.',
    'earn.error': 'Erreur',
    'earn.failedAdd': 'Échec de l\'ajout du point',
    'earn.unexpected': 'Une erreur inattendue est survenue',
    'earn.magicSent': 'Lien magique envoyé',
    'earn.magicDesc': 'Vérifiez vos e-mails pour lier votre compte et gagner un point bonus !',
    'earn.failedMagic': 'Échec de l\'envoi du lien magique',
    'earn.oops': 'Oups !',
    'earn.wrong': 'Quelque chose s\'est mal passé',
    'earn.digitalCard': 'Carte de Fidélité Numérique',
    'earn.rewardUnlocked': '🎉 Récompense débloquée !',
    'earn.showScreen': 'Montrez cet écran au personnel pour obtenir votre récompense.',
    'earn.redeem': 'Obtenir la récompense',
    'earn.validate': 'Valider mon achat',
    'earn.savePoints': 'Sauvegarder mes points',
    'earn.recent': 'Activité Récente',
    'earn.plusOne': '+1 Point',
    'earn.saveTitle': 'Sauvegardez vos points',
    'earn.saveDesc': 'Entrez votre e-mail pour sauvegarder votre progression. Nous vous enverrons un lien magique pour vous connecter. Gagnez un point bonus en vous connectant !',
    'earn.email': 'Adresse e-mail',
    'earn.sendMagic': 'Envoyer le lien magique',
    'earn.waitingValidation': 'En attente de validation',
    'earn.askMerchant': 'Veuillez demander au commerçant d\'approuver votre scan.',
    'earn.validationRejected': 'Validation refusée',
    'earn.merchantRejected': 'Le commerçant a refusé votre demande de validation.',
    'earn.closeTab': 'Fermer l\'onglet',
    'earn.cooldown': 'Patienter avant de scanner',
    'earn.qrExpired': 'QR code expiré',
    'earn.qrExpiredTitle': 'QR code expiré',
    'earn.qrExpiredDesc': 'Ce QR code a expiré. Demandez au commerçant de le rafraîchir, puis scannez à nouveau.',
    'earn.close': 'Fermer',
    'earn.eduDesc': 'Vos points sont sauvegardés dans ce navigateur. Changer de téléphone ou vider vos données pourrait vous les faire perdre.',
    'earn.eduCta': 'Liez votre compte — c\'est gratuit et prend 10 secondes.',
    'earn.protectTitle': 'Protégez vos points',
    'earn.protectDesc': 'Connectez-vous pour sauvegarder vos points sur tous vos appareils.',
    'earn.saveWithGoogle': 'Continuer avec Google',
    'earn.saveWithFacebook': 'Continuer avec Facebook',
    'earn.or': 'ou',
    'merchant.failedLoad': 'Échec du chargement du tableau de bord',
    'merchant.configSaved': 'Configuration sauvegardée avec succès',
    'merchant.failedConfig': 'Échec de la sauvegarde de la configuration',
    'merchant.copied': 'Copié dans le presse-papiers',
    'merchant.failedData': 'Échec du chargement des données du commerçant.',
    'merchant.title': 'Trelio',
    'merchant.logout': 'Déconnexion',
    'merchant.welcome': 'Bienvenue, ',
    'merchant.manage': 'Gérez votre programme de fidélité et suivez vos performances.',
    'merchant.overview': 'Aperçu',
    'merchant.settings': 'Paramètres',
    'merchant.integration': 'Intégration',
    'merchant.totalScans': 'Scans Totaux',
    'merchant.uniqueUsers': 'Clients Uniques',
    'merchant.rewardsRedeemed': 'Récompenses Obtenues',
    'merchant.programConfig': 'Configuration du Programme',
    'merchant.storeName': 'Nom de la boutique',
    'merchant.rewardThreshold': 'Seuil de récompense (Points nécessaires)',
    'merchant.rewardDesc': 'Description de la récompense',
    'merchant.egCoffee': 'ex: Café Gratuit',
    'merchant.showQrCode': 'Afficher mon QR code',
    'merchant.backToDashboard': 'Retour au tableau de bord',
    'merchant.failedLoadQr': 'Échec du chargement du code QR',
    'merchant.scanQrDesc': 'Scannez ce code QR pour gagner des points de fidélité. Il se met à jour automatiquement toutes les 60 secondes.',
    'merchant.validationRequests': 'Demandes de validation',
    'merchant.waitingCustomers': 'En attente de scan par les clients...',
    'merchant.newRequest': 'Nouvelle demande',
    'merchant.approve': 'Approuver',
    'merchant.reject': 'Refuser',
    'merchant.requestApproved': 'Demande approuvée',
    'merchant.requestRejected': 'Demande refusée',
    'merchant.failedProcessRequest': 'Échec du traitement de la demande',
    'merchant.validationMode': 'Mode de validation',
    'merchant.validationModeDesc': 'Choisissez comment les clients gagnent des points.',
    'merchant.modeAutomatic': 'Automatique',
    'merchant.modeAutomaticDesc': 'Les points sont ajoutés instantanément lorsqu\'un client scanne et valide.',
    'merchant.modeManual': 'Manuel',
    'merchant.modeManualDesc': 'Vous devez approuver chaque demande de validation en temps réel.',
    'merchant.saveChanges': 'Sauvegarder les modifications',
    'merchant.apiCreds': 'Identifiants API',
    'merchant.useCreds': 'Utilisez ces identifiants pour générer des QR codes sur vos appareils e-ink.',
    'merchant.merchantId': 'ID Commerçant',
    'merchant.secretKey': 'Clé Secrète',
    'merchant.keepSecret': 'Gardez ceci secret',
    'merchant.doNotShare': 'Ne partagez pas votre clé secrète. Elle est utilisée pour signer les QR codes et éviter la fraude.',
    'merchant.recentScans': 'Scans Récents',
    'merchant.searchPlaceholder': 'Rechercher un e-mail ou ID d\'appareil...',
    'merchant.filter': 'Filtrer',
    'merchant.dateAndTime': 'Date & Heure',
    'merchant.customer': 'Client',
    'merchant.type': 'Type',
    'merchant.device': 'Appareil',
    'merchant.anonymous': 'Anonyme',
    'merchant.registered': 'Inscrit',
    'merchant.noScans': 'Aucun scan ne correspond à vos filtres.',
    'merchant.showing': 'Affichage de',
    'merchant.to': 'à',
    'merchant.of': 'sur',
    'merchant.results': 'résultats',
    'merchant.previous': 'Précédent',
    'merchant.next': 'Suivant',
    'sim.failedLoad': 'Échec du chargement du QR code',
    'sim.checkEnv': 'Échec du chargement du QR code. Vérifiez les variables d\'environnement.',
    'sim.scan': 'Scannez pour gagner des points !',
    'sim.coffee': '1 café = 1 point',
    'sim.action': 'Action Simulateur',
    'sim.openView': 'Ouvrir la vue client dans un nouvel onglet',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setMounted(true)
    const saved = localStorage.getItem('language') as Language
    if (saved && (saved === 'en' || saved === 'fr')) {
      setLanguage(saved)
    } else {
      const browserLang = navigator.language.startsWith('fr') ? 'fr' : 'en'
      setLanguage(browserLang)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string) => {
    if (!mounted) return translations['en'][key as keyof typeof translations['en']] || key
    return translations[language][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
